parameters:
#    gie_amqp.example.class: Gie\AmqpBundle\Example

services:
#    gie_amqp.example:
#        class: %gie_amqp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
